import { IUsuario } from "./models";

type UsuarioLogin = {
  correo: string;
  password: string;
};
type UsuarioLoginResp = {
  ok: boolean;
  usuario: IUsuario | null;
  token: string | null;
  msg: string;
};
type UsuarioRegister = {
  nombre: string;
  correo: string;
  password: string;
};
type errorObj = {
  value?: string;
  msg: string;
  param: string;
  location: string;
};
type UsuarioRegisterResp = {
  ok: boolean;
  msg: string;
  body: { usuario: IUsuario; token: string } | null;
  errors: errorObj[] | null;
};
interface ProductInfo {
  _id: string;
  nombre: string;
  nombre_empresa: string;
  precio: number;
  categoria: { nombre: string; _id: string };
  descripcion: string;
  descuento: number;
}

// Generated by https://quicktype.io

export interface CategoriasConUsuarios {
  _id: string;
  nombre: string;
  estado: boolean;
  usuario: string;
  __v: number;
  productos: Productos[];
}

export interface Productos {
  _id: string;
  nombre: string;
  estado: boolean;
  usuario: string;
  precio: number;
  categoria: string;
  descripcion: string;
  imgs: string[];
  disponible: boolean;
  sexo: string;
  nombre_empresa: string;
  descuento: number;
  __v: number;
}

export type {
  UsuarioLogin,
  UsuarioLoginResp,
  UsuarioRegister,
  UsuarioRegisterResp,
  ProductInfo,
};
